version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true
hooks:
  BeforeInstall:
    - location: deploy_scripts/install_environment_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy_scripts/start_server.sh
      timeout: 30
      runas: root
    - location: deploy_scripts/install_project_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deploy_scripts/stop_server.sh
      timeout: 30
      runas: root
